# Generated by Django 4.2.9 on 2024-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=False)),
                ('redirect_to', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_image', models.ImageField(upload_to='logos/')),
                ('desktop_image', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
