# Generated by Django 4.2.9 on 2024-03-10 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('theme_color', models.CharField(default='#ffffff', max_length=10)),
                ('icon', models.ImageField(null=True, upload_to='party_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='OpenGraphMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='og_images/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('party', models.UUIDField()),
                ('address_pattern', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('header_data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='site_appearance.headerdata')),
                ('og_metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='site_appearance.opengraphmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_image', models.ImageField(upload_to='banners/')),
                ('desktop_image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=False)),
                ('redirect_to', models.URLField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='site_appearance.page')),
            ],
        ),
    ]
