# Generated by Django 4.2.9 on 2024-03-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerdata',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
