# Generated by Django 4.2.9 on 2024-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('theme_color', models.CharField(default='#ffffff', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpenGraphMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='og_images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
