# Generated by Django 4.2.9 on 2024-03-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0002_alter_headerdata_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='appbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_appearance.appbar'),
        ),
    ]
