# Generated by Django 4.2.9 on 2024-02-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0003_opengraphmetadata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerdata',
            name='icon',
            field=models.ImageField(null=True, upload_to='party_icons/'),
        ),
    ]
