# Generated by Django 4.2.9 on 2024-03-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_logo_opengraphmetadata_and_more'),
        ('site_appearance', '0004_headerdata_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.UUIDField()),
                ('address_pattern', models.CharField(max_length=100)),
                ('header_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='site_appearance.headerdata')),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='OpenGraphMetaData',
        ),
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_appearance.page'),
            preserve_default=False,
        ),
    ]
