# Generated by Django 4.2.9 on 2024-03-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0005_page_delete_logo_delete_opengraphmetadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banners', to='site_appearance.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='page', to='site_appearance.headerdata'),
        ),
    ]
