# Generated by Django 4.2.9 on 2024-03-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0006_page_order_alter_banner_page_alter_page_header_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraphMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='og_images/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='og_metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page', to='site_appearance.opengraphmetadata'),
        ),
    ]
