# Generated by Django 4.2.9 on 2024-03-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_appearance', '0007_opengraphmetadata_page_og_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opengraphmetadata',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
