# Generated by Django 4.2.9 on 2024-03-10 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_image', models.ImageField(upload_to='logos/')),
                ('desktop_image', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=25)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_name', models.CharField(max_length=20)),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='party', to='party.logo')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='party.party')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('party.party',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='party.party')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('party.party',),
        ),
        migrations.CreateModel(
            name='PartyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.party')),
            ],
            options={
                'unique_together': {('party', 'domain')},
            },
        ),
    ]
