# Generated by Django 4.2.9 on 2024-03-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(help_text='The name is uniqe. The name is used for retrieving party information.', max_length=50, unique=True),
        ),
    ]
