# Generated by Django 4.2.9 on 2024-02-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='party.party')),
            ],
            options={
                'unique_together': {('party', 'domain')},
            },
        ),
    ]
