# Generated by Django 4.2.9 on 2024-03-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_alter_party_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenGraphMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='og_images/')),
                ('url', models.URLField()),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='og_metadata', to='party.party')),
            ],
        ),
    ]
