# Generated by Django 4.2.9 on 2024-02-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_logo_party_main_page_header_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='display_name',
            field=models.CharField(max_length=10),
        ),
    ]
