# Generated by Django 4.2.9 on 2024-03-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_alter_party_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_image', models.ImageField(upload_to='logos/')),
                ('desktop_image', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='OpenGraphMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='og_images/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='party',
            name='main_page_header_data',
        ),
        migrations.RemoveField(
            model_name='party',
            name='main_page_og_metadata',
        ),
        migrations.AddField(
            model_name='party',
            name='og_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party', to='party.opengraphmetadata', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='party', to='party.logo'),
            preserve_default=False,
        ),
    ]
