# Generated by Django 4.2.9 on 2024-03-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_logo_opengraphmetadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='og_metadata',
        ),
        migrations.DeleteModel(
            name='OpenGraphMetaData',
        ),
    ]
