# Generated by Django 4.2.9 on 2024-03-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_remove_party_og_metadata_delete_opengraphmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
